import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AstraScreen, DemoPill, SectionHeading } from "@/components/astra/ui";
import { HospitalCard } from "@/components/astra/hospital-card";
import { useAstra } from "@/lib/astra/store";
import { HospitalRecommendationEngine } from "@/lib/astra/recommendation";
import type { RankedHospital } from "@/types/astra";

export default function HospitalsScreen() {
  const router = useRouter(); const { hospitals, currentLocation } = useAstra(); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"Best match" | "Fastest" | "Most available">("Best match"); const engine = useMemo(() => new HospitalRecommendationEngine(), []);
  // ⚡ Optimization: Memoize base ranking on hospitals/location changes so search queries and filter changes do not re-calculate scores and distances on every keystroke.
  const ranked = useMemo(() => engine.rank("general", currentLocation, hospitals), [engine, currentLocation, hospitals]);
  const results = useMemo(() => { const filtered = query.trim() ? ranked.filter(({ hospital }) => `${hospital.name} ${hospital.specialties.join(" ")}`.toLowerCase().includes(query.toLowerCase())) : ranked; if (filter === "Fastest") return [...filtered].sort((a, b) => a.score.etaMinutes - b.score.etaMinutes); if (filter === "Most available") return [...filtered].sort((a, b) => b.hospital.beds.icu - a.hospital.beds.icu); return filtered; }, [ranked, query, filter]);
  // ⚡ Optimization: Memoize renderItem callback so FlatList receives a stable reference, allowing React.memo(HospitalCard) to skip re-rendering unchanged cards.
  const renderItem = useCallback(({ item }: { item: RankedHospital }) => <HospitalCard item={item} />, []);
  return <AstraScreen back title="Find a hospital"><View style={styles.header}><DemoPill /><Text style={styles.title}>Emergency hospitals</Text><Text style={styles.subtitle}>Compare readiness, capacity, travel time, and freshness.</Text></View><View style={styles.search}><MaterialIcons name="search" size={20} color="#536273" /><TextInput value={query} onChangeText={setQuery} placeholder="Search hospital or specialty" placeholderTextColor="#8A98A6" style={styles.input} /><MaterialIcons name="tune" size={20} color="#0B78C6" /></View><View style={styles.filters}>{(["Best match", "Fastest", "Most available"] as const).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</View><SectionHeading title={`${results.length} hospitals connected`} action={<Pressable onPress={() => router.push("/map" as never)}><Text style={styles.mapLink}>Map view</Text></Pressable>} /><FlatList data={results} keyExtractor={(item) => item.hospital.id} renderItem={renderItem} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="search-off" size={42} color="#0B78C6" /><Text style={styles.emptyTitle}>No hospitals found</Text><Text style={styles.emptyBody}>Try another search or remove the filter.</Text></View>} contentContainerStyle={{ paddingBottom: 30 }} /></AstraScreen>;
}
const styles = StyleSheet.create({ header: { paddingHorizontal: 20, paddingTop: 14 }, title: { color: "#0B2942", fontSize: 28, fontWeight: "900", marginTop: 20 }, subtitle: { color: "#536273", fontSize: 13, marginTop: 6 }, search: { margin: 20, marginBottom: 4, minHeight: 50, backgroundColor: "#FFFFFF", borderRadius: 14, borderWidth: 1, borderColor: "#E4EBF1", alignItems: "center", flexDirection: "row", paddingHorizontal: 14, gap: 9 }, input: { flex: 1, color: "#0B2942", fontSize: 13 }, filters: { flexDirection: "row", gap: 7, marginHorizontal: 20 }, filter: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: 9, backgroundColor: "#EEF3F7" }, filterActive: { backgroundColor: "#0B78C6" }, filterText: { color: "#536273", fontSize: 11, fontWeight: "800" }, filterTextActive: { color: "#FFFFFF" }, mapLink: { color: "#0B78C6", fontSize: 12, fontWeight: "800" }, empty: { alignItems: "center", padding: 40 }, emptyTitle: { color: "#0B2942", fontSize: 18, fontWeight: "900", marginTop: 12 }, emptyBody: { color: "#536273", fontSize: 12, marginTop: 5 } });
