import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { AstraScreen, DemoPill, PrimaryButton, StatusPill } from "@/components/astra/ui";
import { LiveMap } from "@/components/astra/live-map";
import { useAstra } from "@/lib/astra/store";
import { requestCurrentLocation, watchCurrentLocation } from "@/lib/location-service";
import { fetchLiveRoute, type RoutePoint } from "@/lib/routing-service";

export default function MapScreen() {
  const router = useRouter();
  const { hospitals, activeEmergency, currentLocation, setCurrentLocation } = useAstra();
  const [locationMessage, setLocationMessage] = useState("");
  const [routeCoordinates, setRouteCoordinates] = useState<RoutePoint[]>([]);
  const [routeMode, setRouteMode] = useState<"live" | "fallback">("fallback");
  const [routeRetry, setRouteRetry] = useState(0);
  const selected = useMemo(() => hospitals.find((item) => item.id === activeEmergency?.selectedHospitalId) ?? hospitals[0], [hospitals, activeEmergency?.selectedHospitalId]);
  useEffect(() => { let subscription: { remove: () => void } | undefined; requestCurrentLocation().then((result) => { if (result.location) setCurrentLocation(result.location); if (result.error) setLocationMessage(result.error); }).catch(() => setLocationMessage("Unable to access your location; showing the last known position.")); watchCurrentLocation(setCurrentLocation, setLocationMessage).then((next) => { subscription = next; }).catch(() => undefined); return () => subscription?.remove(); }, [setCurrentLocation]);
  useEffect(() => { if (!selected) return; setRouteMode("fallback"); fetchLiveRoute(currentLocation, selected.location).then((route) => { setRouteCoordinates(route); setRouteMode(route.length > 2 ? "live" : "fallback"); }).catch(() => { setRouteCoordinates([{ latitude: currentLocation.latitude, longitude: currentLocation.longitude }, { latitude: selected.location.latitude, longitude: selected.location.longitude }]); setRouteMode("fallback"); setLocationMessage("Live route unavailable; showing a direct fallback line."); }); }, [currentLocation, selected, routeRetry]);
  return <AstraScreen back title="Live route"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><DemoPill /><Text style={styles.title}>Live route</Text><Text style={styles.subtitle}>Native map, live device location, and route markers for iOS and Android.</Text></View>{locationMessage && <View style={styles.locationNotice}><MaterialIcons name="location-off" size={17} color="#A86A00" /><Text style={styles.locationText}>{locationMessage}</Text></View>}<View style={styles.map}><LiveMap location={currentLocation} hospitals={hospitals} selectedHospitalId={selected?.id} ambulanceLocation={activeEmergency?.ambulance?.location} routeCoordinates={routeCoordinates} routeMode={routeMode} /></View>{routeMode === "fallback" && <View style={styles.fallbackCard}><View style={{ flex: 1 }}><Text style={styles.fallbackTitle}>Offline route preview</Text><Text style={styles.fallbackText}>A straight-line estimate is shown until road geometry is available.</Text></View><PrimaryButton label="Retry" tone="quiet" onPress={() => setRouteRetry((value) => value + 1)} /></View>}<Text style={styles.attribution}>© OpenStreetMap contributors · Routing by OSRM-compatible service</Text><View style={styles.sheet}><Text style={styles.eyebrow}>RECOMMENDED DESTINATION</Text><Text style={styles.hospital}>{selected?.name ?? "No hospital selected"}</Text><Text style={styles.address}>{selected?.address}</Text><View style={styles.sheetRow}><View><Text style={styles.value}>{activeEmergency?.recommendation?.etaMinutes ?? 8} min</Text><Text style={styles.label}>estimated arrival</Text></View><View><Text style={styles.value}>{activeEmergency?.recommendation?.distanceKm ?? 2.8} km</Text><Text style={styles.label}>distance</Text></View><StatusPill status={selected?.readiness ?? "unknown"} /></View><PrimaryButton label="Continue emergency session" icon="navigation" onPress={() => router.push("/emergency" as never)} /></View></ScrollView></AstraScreen>;
}
const styles = StyleSheet.create({ content: { paddingBottom: 35 }, header: { paddingHorizontal: 20, paddingTop: 14 }, title: { color: "#0B2942", fontSize: 28, fontWeight: "900", marginTop: 20 }, subtitle: { color: "#536273", fontSize: 12, lineHeight: 18, marginTop: 6 }, locationNotice: { margin: 20, marginBottom: 0, padding: 11, borderRadius: 13, backgroundColor: "#FFF6E1", flexDirection: "row", alignItems: "center", gap: 8 }, locationText: { color: "#795200", flex: 1, fontSize: 11, lineHeight: 16 }, map: { height: 330, margin: 20, marginBottom: 0, borderRadius: 22, overflow: "hidden", backgroundColor: "#DCEEF2" }, fallbackCard: { marginHorizontal: 20, marginTop: 10, padding: 12, borderRadius: 14, backgroundColor: "#FFF6E1", flexDirection: "row", alignItems: "center", gap: 10 }, fallbackTitle: { color: "#795200", fontSize: 12, fontWeight: "900" }, fallbackText: { color: "#795200", fontSize: 10, lineHeight: 14, marginTop: 3 }, attribution: { marginHorizontal: 20, marginTop: 7, color: "#536273", fontSize: 10 }, sheet: { margin: 20, marginTop: 14, padding: 17, borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E4EBF1" }, eyebrow: { color: "#0B78C6", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, hospital: { color: "#0B2942", fontSize: 19, fontWeight: "900", marginTop: 7 }, address: { color: "#536273", fontSize: 12, marginTop: 4 }, sheetRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginVertical: 15 }, value: { color: "#0B2942", fontSize: 18, fontWeight: "900" }, label: { color: "#536273", fontSize: 10, marginTop: 2 } });
