import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useMemo } from "react";
import { HospitalCard } from "@/components/astra/hospital-card";
import { AstraScreen, DemoPill, PrimaryButton, SafetyNotice, SectionHeading, StatusPill } from "@/components/astra/ui";
import { useAstra } from "@/lib/astra/store";
import { HospitalRecommendationEngine } from "@/lib/astra/recommendation";
import { emergencyLabels } from "@/types/astra";

export default function RecommendationScreen() {
  const router = useRouter();
  const params = useLocalSearchParams<{ emergencyId?: string }>();
  const { activeEmergency, hospitals, selectHospital } = useAstra();
  const engine = useMemo(() => new HospitalRecommendationEngine(), []);
  const session = activeEmergency;
  const ranked = useMemo(() => session ? engine.rank(session.type, session.patientLocation, hospitals) : [], [engine, session, hospitals]);
  const best = ranked.find((item) => item.hospital.id === session?.recommendation?.hospitalId) ?? ranked[0];
  if (!session || !best) return <AstraScreen back><View style={styles.empty}><MaterialIcons name="search-off" size={48} color="#0B78C6" /><Text style={styles.emptyTitle}>No recommendation available</Text><Text style={styles.emptyBody}>Try another emergency type or enter a different location.</Text></View></AstraScreen>;
  const confirm = () => { selectHospital(best.hospital.id); router.push("/emergency" as never); };
  return <AstraScreen back title="ASTRA recommendation"><ScrollView contentContainerStyle={styles.content}><DemoPill /><Text style={styles.eyebrow}>BEST MATCH · {emergencyLabels[session.type].toUpperCase()}</Text><Text style={styles.title}>The right hospital, explained.</Text><Text style={styles.subtitle}>Ranked using clinical fit, capacity, specialist status, travel time, readiness, and data freshness.</Text><View style={styles.hero}><View style={styles.heroTop}><View style={{ flex: 1 }}><Text style={styles.recLabel}>ASTRA RECOMMENDS</Text><Text style={styles.hospitalName}>{best.hospital.name}</Text><Text style={styles.hospitalAddress}>{best.hospital.address}</Text></View><View style={styles.match}><Text style={styles.matchValue}>{best.score.overall}%</Text><Text style={styles.matchLabel}>overall match</Text></View></View><View style={styles.heroStatus}><StatusPill status={best.hospital.readiness} /><Text style={styles.verified}><MaterialIcons name="verified" size={15} color="#1E7A52" /> Confirmed {Math.max(1, Math.round((Date.now() - new Date(best.hospital.dataLastUpdated).getTime()) / 60000))} min ago</Text></View></View><View style={styles.breakdown}>{[{ label: "Clinical match", value: best.score.clinical, icon: "local-hospital" }, { label: "Availability", value: best.score.availability, icon: "airline-seat-flat" }, { label: "Travel time", value: best.score.travel, icon: "schedule" }, { label: "Specialist", value: best.score.specialist, icon: "person" }, { label: "Data freshness", value: best.score.freshness, icon: "update" }].map((metric) => <View key={metric.label} style={styles.breakRow}><View style={styles.breakLabel}><MaterialIcons name={metric.icon as never} size={16} color="#0B78C6" /><Text style={styles.breakText}>{metric.label}</Text></View><View style={styles.bar}><View style={[styles.barFill, { width: `${metric.value}%` }]} /></View><Text style={styles.percent}>{metric.value}%</Text></View>)}</View><View style={styles.reasonBox}><Text style={styles.reasonTitle}>Why this is the best match</Text>{best.score.reasons.map((reason) => <View key={reason} style={styles.reason}><MaterialIcons name="check" size={16} color="#1E7A52" /><Text style={styles.reasonText}>{reason}</Text></View>)}</View><SafetyNotice compact /><PrimaryButton label={`Confirm ${best.score.etaMinutes} min route`} icon="navigation" onPress={confirm} /><SectionHeading eyebrow="ALTERNATIVES" title="Compare other hospitals" /><View>{ranked.slice(1, 4).map((item) => <HospitalCard key={item.hospital.id} item={item} />)}</View><Text style={styles.disclaimer}>AI-assisted recommendation. Final medical decisions remain with patients, paramedics, and healthcare professionals. Hospital availability is simulated demo data.</Text></ScrollView></AstraScreen>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 40 }, eyebrow: { color: "#0B78C6", fontSize: 10, letterSpacing: 1, fontWeight: "900", marginHorizontal: 20, marginTop: 22 }, title: { color: "#0B2942", fontSize: 28, lineHeight: 34, fontWeight: "900", marginHorizontal: 20, marginTop: 8 }, subtitle: { color: "#536273", fontSize: 13, lineHeight: 19, marginHorizontal: 20, marginTop: 8 }, hero: { margin: 20, padding: 18, borderRadius: 20, backgroundColor: "#0B2942" }, heroTop: { flexDirection: "row" }, recLabel: { color: "#8DC7EE", fontSize: 10, letterSpacing: 1, fontWeight: "900" }, hospitalName: { color: "#FFFFFF", fontSize: 20, lineHeight: 25, fontWeight: "900", marginTop: 8 }, hospitalAddress: { color: "#B9CBD7", fontSize: 11, lineHeight: 16, marginTop: 4 }, match: { alignItems: "flex-end", marginLeft: 8 }, matchValue: { color: "#8DD5B0", fontSize: 32, lineHeight: 36, fontWeight: "900" }, matchLabel: { color: "#B9CBD7", fontSize: 10, fontWeight: "700" }, heroStatus: { flexDirection: "row", alignItems: "center", marginTop: 18, gap: 10 }, verified: { color: "#B9CBD7", fontSize: 11, flexDirection: "row", alignItems: "center" }, breakdown: { marginHorizontal: 20, padding: 16, borderRadius: 18, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E4EBF1", gap: 15 }, breakRow: { flexDirection: "row", alignItems: "center", gap: 9 }, breakLabel: { width: 115, flexDirection: "row", alignItems: "center", gap: 6 }, breakText: { color: "#294155", fontSize: 11, fontWeight: "700" }, bar: { flex: 1, height: 7, backgroundColor: "#EAF0F4", borderRadius: 9, overflow: "hidden" }, barFill: { height: "100%", borderRadius: 9, backgroundColor: "#0B78C6" }, percent: { width: 35, color: "#0B2942", fontSize: 11, textAlign: "right", fontWeight: "800" }, reasonBox: { marginHorizontal: 20, marginTop: 14, padding: 16, borderRadius: 17, backgroundColor: "#EAF4FC" }, reasonTitle: { color: "#0B2942", fontSize: 14, fontWeight: "900", marginBottom: 10 }, reason: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 7 }, reasonText: { color: "#294155", fontSize: 12, fontWeight: "600" }, disclaimer: { color: "#748395", fontSize: 11, lineHeight: 16, textAlign: "center", marginHorizontal: 28, marginTop: 18 }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 30 }, emptyTitle: { color: "#0B2942", fontSize: 20, fontWeight: "900", marginTop: 15 }, emptyBody: { color: "#536273", textAlign: "center", marginTop: 8 } });
